before_script:
    - composer install
    - composer require --dev phpstan/phpstan

phpstan:
    script:
        - vendor/bin/phpstan analyze -l 4 ./danaketh/HubSpot/

phpunit:
    script:
        - vendor/bin/phpunit --configuration=phpunit.xml --coverage-text
